spring:
  application:
    name: PicPay-Simplificado
  datasource:
    url: jdbc:h2:mem:teste
    username: sa
    password:
  h2:
    console:
    enabled: true
    path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api
